### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by azachar** [ibrod1983/nodejs-web-scraper#1]
Ahoj, 

Thank you for a great tool!

is it possible to name files instead of using the md5 hashes? For instance, on the download page, there is a title and I want to name my downloadable file with that name.  (Think of this page: https://link.springer.com/book/10.1007%2F978-0-387-84858-7)

How should I proceed?

Thank you!

**Comment by ibrod1983** [comment]
Hey,
Unfortunately i don't see any "reasonable" way to do this with my current API. The scenario where the user might want to dynamically choose the name of the file, didn't really occur to me, when i was writing this program.

Thank you for pointing this out. I will think of some new feature that will take care of this, but i'm sure you will find some workaround/different tool, until that happens :D

**Comment by ibrod1983** [comment]
Azachar, i have few questions  for you:

1) What did you mean by "instead of using md5 hashes"? What hash are you referring to? 
2) Do you have any idea, how the browser "deduces" the name of the file, when we do right-click+save as? I see that a human-readable name appears, but i have no clue where this name comes from.

**Comment by ibrod1983** [comment]
I just published a new version. It will take into account **Content-Disposition: filename=somefilename.extension**, when downloading files, like your pdf's. Now, the files will have meaningful name as received from the server.

**Comment by azachar** [comment]
Thank you!

Best regards,
Andrej Zachar

+32489085724
